#!/bin/bash

target=$1

#-----------------------------------------------------------------------
# CMake build directory
#-----------------------------------------------------------------------
builddir=build

# Create the build directory and run cmake if needed
if [ ! -f "$builddir/Makefile" ]; then
    mkdir -p "$builddir"
    cmake -S . -B "$builddir" "${@:2}"
fi

#-----------------------------------------------------------------------
# Build and install
#-----------------------------------------------------------------------
if [ -z "$target" ]; then
    cmake --build "$builddir"
else
    cmake --build "$builddir" --target "${target}.x"
fi

cmake --install "$builddir" --prefix .
