#!/bin/bash

target=$1

#-----------------------------------------------------------------------
# Calls to make
#-----------------------------------------------------------------------
list=(displace blockdiag kdc pltkdc)

if [ -z $target ]; then
    for T in "${list[@]}"; do
	make $T $args
    done
else
    make $target $args
fi
